### ISSUE TITLE
Old react peerDep version

### ISSUE THREAD

**Issue by kamerat** [Gobi-Stories/gobi-sanity#2]
In the peerDependencies, you are using react ^16. Is this project dependent on 16 or is it possible to bump it to ^17? 

https://github.com/Gobi-Stories/gobi-sanity/blob/dc5dfdd7e5b3490f9aafb8ce6f06e10c4bff58a9/package.json#L27

When trying to install this plugin in a a workspace where react > 16 && NPM > v6 it crashes due to NPM's new way of handling peers.

![image](https://user-images.githubusercontent.com/11461961/155717137-036dc820-62a5-41cb-99bc-2122edf717c4.png)

**Comment by marcoacfilho** [comment]
React version has been updated

**Comment by kamerat** [comment]
Hi again, awesome release! However, I think it's the peerDependencies that has to be updated to ^17 ☺️ If I am not mistaking. I still get the error here.

EDIT: Now that the peerDeps is updated in https://github.com/Gobi-Stories/gobi-sanity/commit/1e49d39adb3c6f2e2cb541d5b12cc47c3042a538, it works wonderfully.
